### ISSUE TITLE
CODE REFACTORING

### ISSUE THREAD

**Issue by RohithChittibommala** [Club-Collabaration/club-collaboration-frontend#13]
@iiitv/project-maintainers  I WOULD LIKE TO REFACTOR THE CODE

**Comment by theyashshahs** [comment]
@RohithChittibommala what part you want to refactor?

**Comment by RohithChittibommala** [comment]
https://github.com/iiitv/club-collaboration-frontend/blob/master/src/main-page/navbar/main%20navbar/navbar.js

<blockquote><img src="https://avatars1.githubusercontent.com/u/9347727?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/iiitv/club-collaboration-frontend">iiitv/club-collaboration-frontend</a></strong></div><div>Development Link -. Contribute to iiitv/club-collaboration-frontend development by creating an account on GitHub.</div></blockquote>
