### ISSUE TITLE
create login page

### ISSUE THREAD

**Issue by RohithChittibommala** [Club-Collabaration/club-collaboration-frontend#15]
I would like to work on this issue @iiitv/project-maintainers

**Comment by theyashshahs** [comment]
Do you have the required designs for the same.

**Comment by RohithChittibommala** [comment]
@yashshah2820   sir can I implement this design?
![image](https://user-images.githubusercontent.com/62145732/93974278-39cd5800-fd93-11ea-9703-369e4aadd909.png)

**Comment by theyashshahs** [comment]
@RohithChittibommala GFI 👍
