### ISSUE TITLE
Enhancement UI rendering in mobile view.

### ISSUE THREAD

**Issue by nlok5923** [Club-Collabaration/club-collaboration-frontend#16]
Some of the elements in the mobile view are not within the boundary.

![WhatsApp Image 2020-09-20 at 7 40 42 AM](https://user-images.githubusercontent.com/56120084/93714060-ea79f400-fb14-11ea-9052-5a3534740a22.jpeg)

@iiitv/project-maintainers i would like to work on this issue.

**Comment by theyashshahs** [comment]
@nlok5923 GFI 👍
