### ISSUE TITLE
Change deployment link.

### ISSUE THREAD

**Issue by nlok5923** [Club-Collabaration/club-collaboration-frontend#22]
Current link doesn't synchronise with the changes done in project.

Example: blur effect on hover on club bar has been added through pr [#11 ](https://github.com/iiitv/club-collaboration-frontend/pull/11).
![Screenshot (1398)](https://user-images.githubusercontent.com/56120084/94666956-fdce5180-02c2-11eb-9ec2-a1fb6a86f11d.png)

@iiitv/project-maintainers i would like to work on it.

**Comment by anshumanv** [comment]
It should have redeployed when changes are merged, issue not relevant. 

Whoever has setup netlify can ensure we redeploy on changes?
