### ISSUE TITLE
css overflow problem 

### ISSUE THREAD

**Issue by ShravaniAK** [Club-Collabaration/club-collaboration-frontend#25]
<img width="1440" alt="Screenshot 2022-10-02 at 1 59 25 PM" src="https://user-images.githubusercontent.com/97099574/193445289-ca2a3c4a-62df-43cd-9593-19e524230d79.png">

the members word is overflowing.

**Comment by AkhileshManda** [comment]
@Im-Madhur-Gupta @kalashshah

**Comment by Im-Madhur-Gupta** [comment]
@ShravaniAK GFI!
