### ISSUE TITLE
Link to home on clicking logo

### ISSUE THREAD

**Issue by Krishna841** [Club-Collabaration/club-collaboration-frontend#34]
Link club logo on Navbar to home page

**Comment by AkhileshManda** [comment]
Hey @Krishna841 I think this feature is already present, if not could you add a few screenshots and explain the issue clearly.

**Comment by Krishna841** [comment]
In the top left corner when one clicks on the words "Club Collaboration" one is taken to home page. This is the addition that I want to contribute.

![image](https://user-images.githubusercontent.com/65186847/194051045-16ecc6ab-c1c4-40a6-83b6-2d58765e145d.png)
![image](https://user-images.githubusercontent.com/65186847/194051086-698754c9-9bd4-4958-bcd5-878e933bd491.png)
