### ISSUE TITLE
Error while setting up the project locally

### ISSUE THREAD

**Issue by s0ham075** [Club-Collabaration/club-collaboration-frontend#61]
{
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
I installed all the dependencies using npm install 
however while running the app using npm start it is showing the above error

**Comment by s0ham075** [comment]
@iiitv/react-maintainers Can I work on this if this feels like a valid issue?

**Comment by AniModi** [comment]
This seems a valid issue. It is occurring due to deprecated dependencies of the project. I am assigning you this issue. Feel free to ping me if you face any difficulty.

**Comment by s0ham075** [comment]
I have created a pr for the same , but its failing the checks , can you guide me how to resolve them?

**Comment by ShravaniAK** [comment]
@s0ham075 You can use nvm and change your node version to 16, and then try running your project !!

**Comment by s0ham075** [comment]
Yes that worked @ShravaniAK .I am closing the PR
