### ISSUE TITLE
Fix routes

### ISSUE THREAD

**Issue by ajayjainn** [Club-Collabaration/club-collaboration-frontend#68]
There is a signup component but no route for it. Also, fix typos in routes.

**Comment by cxy012** [comment]
Hello,
I am a contributor from HacktoberFest and I’m excited about contributing to this project. I noticed that the issue [68] is marked with the hacktoberfest label, and I would love to help out by working on this.
Could you please assign this issue to me so I can start working on it?

**Comment by Anas-github-acc** [comment]
Please assign me this issue
