### ISSUE TITLE
ui enhancements

### ISSUE THREAD

**Issue by RohithChittibommala** [Club-Collabaration/club-collaboration-frontend#9]
I would like to add UI enhancements (add hover, transition effects )

**Comment by RohithChittibommala** [comment]
I would like to work on this issue

**Comment by RohithChittibommala** [comment]
@iiitv/project-maintainers  I would like to add UI enhancements, please let me know whether I can work on this issue or not

**Comment by theyashshahs** [comment]
@RohithChittibommala what will you contribute to in this issue

**Comment by RohithChittibommala** [comment]
hover effects on  links  main logo   club logos            On Aug 31, 2020 9:52 PM, Yash Shah <notifications@github.com> wrote:
@RohithChittibommala what will you contribute to in this issue

**Comment by RohithChittibommala** [comment]
I also want to work on the following issuesWhen the user clicks on the nav links ( say announcement link) Page is blank I think it would be if we provide a message to user about page instead blank pageI also want to modify form On Aug 31, 2020 11:16 PM, myselfrohith@outlook.com wrote: hover effects on  links  main logo   club logos            On Aug 31, 2020 9:52 PM, Yash Shah <notifications@github.com> wrote:
@RohithChittibommala what will you contribute to in this issue

**Comment by theyashshahs** [comment]
@RohithChittibommala please do not create a PR unless the issue is assigned to you
